steps:
  - name: download-deps
    image: golang:1.24
    cache:
      go-mod-cache: /root/go/pkg/mod
    tasks:
      - name: download
        runs: go mod download

  - name: test
    image: golang:1.24
    depends_on:
      - download-deps
    cache:
      go-mod-cache: /root/go/pkg/mod
    tasks:
      - name: run tests
        runs: go test -v ./...
